server:
  port: ${PORT:8080}
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  session:
    persistent: false

security:
  basic:
    enabled: true
  require-ssl: true

spring:
  application:
    name: Kafka Webview
  datasource:
    schema: "classpath:/schema/schema.sql"
    url: "jdbc:h2:file:./data/db"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB

  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: HTML
    encoding: UTF-8
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

## Various App Configs
app:
  name: Kafka Web View
  uploadPath: "./data/uploads"
  key: "SuperSecretKey"
  maxConcurrentWebSocketConsumers: 64
