server:
  port: ${PORT:8080}
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    mbeanregistry:
      enabled: true
  servlet:
    session:
      ## User sessions should not be persistent across service restarts by default.
      persistent: false
      ## User login session timeout after 1 hour (3600 seconds)
      timeout: 3600

spring:
  application:
    name: Kafka Webview
  datasource:
    url: "jdbc:h2:file:./data/db"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    locations: "classpath:schema/migration/{vendor}"
    baselineOnMigrate: true

  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB

  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: HTML
    encoding: UTF-8
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true

# Spring Actuator - global
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  ## Disable LDAP by default
  health:
    ldap:
      enabled: false

# Spring Actuator - Info endpoint
info:
  app:
    name: ${spring.application.name}

## Various App Configs
app:
  name: Kafka Web View
  uploadPath: "./data/uploads"
  cachePath: "./data/cache"
  key: "SuperSecretKey"
  multiThreadedConsumer: true
  maxConcurrentWebConsumers: 32
  maxConcurrentWebSocketConsumers: 64
  consumerIdPrefix: "KafkaWebViewConsumer"
  requireSsl: true
  user:
    enabled: true
    ## Ldap auth settings
    ldap:
      enabled: false
      userDnPattern: "uid={0},ou=people"
      groupSearchBase: "ou=groups"
      groupRoleAttribute: "cn"
      groupSearchFilter: "(uniqueMember={0})"
      passwordAttribute: "userPassword"
      passwordEncoderClass: "org.springframework.security.crypto.password.LdapShaPasswordEncoder"
      adminGroups: ""
      userGroups: ""
      url: "ldap://localhost:63182/dc=example,dc=org"
      ## If LDAP does not allow anonymous access, define the user/password to connect using.
      ## If not required, leave both fields empty
      bindUser:
      bindUserPassword:

