server:
  servlet:
    session:
      persistent: true

spring:
  # H2 Datbase
  h2:
    console:
      ## Disable for release
      enabled: true
      path: /h2

  jpa:
    show-sql: true

app:
  requireSsl: false
  user:
    enabled: true
    ## Ldap auth settings
    ldap:
      enabled: false
